"""Add membership type and balance fields

Revision ID: 6c41dc5c9bea
Revises: 
Create Date: 2025-06-29 21:17:58.499035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c41dc5c9bea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('amount_spent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amount_owed', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('amount_owed')
        batch_op.drop_column('amount_spent')
        batch_op.drop_column('membership_type')

    # ### end Alembic commands ###
